steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', 
          '-t', 'gcr.io/$PROJECT_ID/haproxy-certbot:${_MAYOR_REVISION}.${_MINOR_REVISION}.${_BUILD_ID}', 
          '--build-arg',
          'VCS_REF=`git rev-parse --short HEAD`',          
          '--build-arg',          
          'BUILD_DATE=`$(date -u +"%Y-%m-%dT%H:%M:%SZ")`',      
          '--build-arg',          
          'PROJECT_ID=${PROJECT_ID}',         
          '--build-arg',
          'MAYOR_REVISION=${_MAYOR_REVISION}',
          '--build-arg',
          'MINOR_REVISION=${_MINOR_REVISION}',
          '--build-arg',
          'BUILD_ID=${_BUILD_ID}',    
          '--build-arg',
          'HAPROXY_MAJOR=${_HAPROXY_MAJOR}',  
          '--build-arg',
          'HAPROXY_VERSION=${_HAPROXY_VERSION}',
          '--file=./Dockerfile.${_ARCHITECTURE}',
          '.']
substitutions:  # default values
  _ARCHITECTURE: "armv8"
  _MAYOR_REVISION: "1"
  _MINOR_REVISION: "1"
  _BUILD_ID: "1-SNAPSHOT"
  _HAPROXY_MAJOR: "2.4"
  _HAPROXY_VERSION: "2.4.9"
timeout: 5400s
images:
- 'gcr.io/$PROJECT_ID/haproxy-certbot'