#!/bin/sh
#
# Copyright [2025] [LeMaRiva Tech]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# See: http://www.apache.org/licenses/LICENSE-2.0

ROLE_FILE="/var/run/haproxy_role"

# Only run certbot renew if this node is MASTER
if [ ! -f "${ROLE_FILE}" ] || ! grep -qi "master" "${ROLE_FILE}" 2>/dev/null; then
    echo "[INFO] certbot-renew: Node is not MASTER (role from ${ROLE_FILE}), skipping certbot renew." >&2
    exit 0
fi

# Actual renew command
/usr/bin/certbot -c /usr/local/etc/letsencrypt/cli.ini renew "$@"
