#!/bin/sh
# Copyright [2025] [LeMaRiva Tech]
# Licensed under the Apache License, Version 2.0

HA_PROXY_DIR=/usr/local/etc/haproxy
LE_DIR=/addon_config/le_certs/live
DOMAINS=$(ls "${LE_DIR}" 2>/dev/null)

echo "[INFO] haproxy-refresh: rebuilding HAProxy cert bundles from ${LE_DIR}"

# update certs for HA Proxy
for DOMAIN in ${DOMAINS}; do
  if [ -d "${LE_DIR}/${DOMAIN}" ]; then
    cat "${LE_DIR}/${DOMAIN}/fullchain.pem" "${LE_DIR}/${DOMAIN}/privkey.pem" > "${HA_PROXY_DIR}/certs.d/${DOMAIN}.pem"
  fi
done

# restart haproxy
exec /usr/bin/haproxy-restart
