#!/bin/sh
#
# Copyright [2025] [LeMaRiva Tech]
# Licensed under the Apache License, Version 2.0

nl-qdisc-add --dev=lo --parent=1:4 --id=40: --update plug --buffer
[ -f /etc/haproxy-env ] && . /etc/haproxy-env
/usr/local/sbin/haproxy -f "${HAPROXY_CONFIG_FILE}" -D -p /var/run/haproxy.pid -sf "$(cat /var/run/haproxy.pid)"
nl-qdisc-add --dev=lo --parent=1:4 --id=40: --update plug --release-indefinite
