#!/bin/sh
#
# Copyright [2025] [LeMaRiva Tech]
# Licensed under the Apache License, Version 2.0

cfg_file=$1

if [ -z "$cfg_file" ]; then
    cfg_file="/config/haproxy.cfg"
    echo "No argument supplied, using ${cfg_file}"
    echo "To use config from host fs try \"(docker exec -i container haproxy-check -) < path_to_your_config\""
fi

/usr/local/sbin/haproxy -c -V -f "${cfg_file}"
